<?php

namespace Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class EntitiesSearchProxy extends \Entities\Search implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }
    
    
    public function getId()
    {
        $this->__load();
        return parent::getId();
    }

    public function getIsTemp()
    {
        $this->__load();
        return parent::getIsTemp();
    }

    public function setIsTemp($is_temp)
    {
        $this->__load();
        return parent::setIsTemp($is_temp);
    }

    public function getKeywords()
    {
        $this->__load();
        return parent::getKeywords();
    }

    public function setKeywords($keywords)
    {
        $this->__load();
        return parent::setKeywords($keywords);
    }

    public function getExcludeWords()
    {
        $this->__load();
        return parent::getExcludeWords();
    }

    public function setExcludeWords($exclude_words)
    {
        $this->__load();
        return parent::setExcludeWords($exclude_words);
    }

    public function getUpdated()
    {
        $this->__load();
        return parent::getUpdated();
    }

    public function setUpdated($updated)
    {
        $this->__load();
        return parent::setUpdated($updated);
    }

    public function getNetworks()
    {
        $this->__load();
        return parent::getNetworks();
    }

    public function addNetwork($network)
    {
        $this->__load();
        return parent::addNetwork($network);
    }

    public function getItems()
    {
        $this->__load();
        return parent::getItems();
    }

    public function addToSearchResults($item)
    {
        $this->__load();
        return parent::addToSearchResults($item);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'is_temp', 'keywords', 'exclude_words', 'updated', 'items', 'networks');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}